# Generated by Django 5.0.6 on 2024-06-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='nueva_coleccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_auto', models.CharField(max_length=40)),
                ('descripcion_auto', models.CharField(max_length=200)),
                ('stock_auto', models.IntegerField()),
                ('imagen_auto', models.CharField(max_length=255)),
            ],
        ),
    ]
