# Generated by Django 5.0.6 on 2024-06-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nueva_coleccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nueva_coleccion',
            new_name='NuevaColeccion',
        ),
        migrations.AlterModelTable(
            name='nuevacoleccion',
            table='nueva_coleccion',
        ),
    ]
