# Generated by Django 5.0.6 on 2024-06-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categoria_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios_desc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_accesorio', models.CharField(max_length=50)),
                ('descripcion_accesorio', models.CharField(max_length=200)),
                ('stock_accesorio', models.IntegerField()),
                ('imagen_accesorio', models.CharField(max_length=255)),
            ],
        ),
    ]
