# Generated by Django 5.0.6 on 2024-06-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_accesorios_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios_desc',
            name='precio_accesorio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
