# Generated by Django 5.0.6 on 2024-06-21 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accesorios_desc_precio_accesorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAccesorios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria_acc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_acc', models.CharField(max_length=50)),
                ('precio_acc', models.IntegerField()),
                ('descripcion_acc', models.CharField(max_length=200)),
                ('stock_acc', models.IntegerField()),
                ('imagen_acc', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaaccesorios')),
            ],
        ),
    ]
