# Generated by Django 5.0.1 on 2024-06-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoriaaccesorios_accesorios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
